name: JinYan
version: '${project.version}'
main: org.him.jinyan.JinYan
api-version: '1.19'
description: 作者him，github搜him114514找我
author: him
commands:
  jinyanall:
    description: 禁言所有玩家
  jiechuall:
    description: 解除所有禁言
  jyreload:
    description: 重载此插件
  jyhelp:
    description: 此插件的帮助
  jinyan:
    description: 禁言指定的玩家
    usage: /jinyan <玩家>
  jiechu:
    description: 解除指定玩家的禁言
    usage: /jiechu <玩家>